# Generated by Django 6.0.5 on 2026-09-26 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_studentacademicassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_counties', models.TextField(help_text='Comma-separated preferred counties, for example Kisumu, Nakuru, Nairobi.')),
                ('attachment_field', models.CharField(help_text="The student's preferred attachment field.", max_length=200)),
                ('placement_mode', models.CharField(choices=[('any', 'Any Placement Mode'), ('physical', 'Physical'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='any', max_length=20)),
                ('expected_start_date', models.DateField()),
                ('duration_weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('additional_requirements', models.TextField(blank=True, default='')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_verification', 'Awaiting Verification'), ('awaiting_payment', 'Awaiting Payment'), ('active', 'Active'), ('matching', 'Matching in Progress'), ('placed', 'Placement Found'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_assistance_request', to='academics.studentacademicassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('mpesa_sandbox', 'M-Pesa Sandbox'), ('mpesa', 'M-Pesa')], default='mpesa_sandbox', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1500.00'))])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('phone_number', models.CharField(help_text='Use Kenyan international format, for example 254712345678.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter the phone number in Kenyan international format, for example 254712345678.', regex='^254(?:7|1)\\d{8}$')])),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Customer Response'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled by Customer'), ('timed_out', 'Timed Out'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=30)),
                ('result_description', models.TextField(blank=True, default='')),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='payments.placementassistancerequest')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_method', models.CharField(choices=[('academic_record', 'Institution Academic Record'), ('student_id', 'Student ID Document'), ('manual', 'Manual Institution Review')], default='academic_record', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('student_id_document', models.ImageField(blank=True, null=True, upload_to='student_verification_ids/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('institution_notes', models.TextField(blank=True, default='')),
                ('document_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_verification', to='academics.studentacademicassignment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifications_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='placementassistancerequest',
            name='verification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement_request', to='payments.studentverification'),
        ),
        migrations.CreateModel(
            name='PaymentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Payment Created'), ('stk_requested', 'STK Push Requested'), ('stk_accepted', 'STK Request Accepted'), ('callback_received', 'Callback Received'), ('status_changed', 'Status Changed'), ('query_performed', 'Status Query Performed'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_events', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='payment_audit_event_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'initiated_at'], name='payment_tx_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['phone_number', 'initiated_at'], name='payment_tx_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='studentverification',
            index=models.Index(fields=['status', 'submitted_at'], name='payment_verify_status_idx'),
        ),
        migrations.AddIndex(
            model_name='placementassistancerequest',
            index=models.Index(fields=['status', 'created_at'], name='payment_request_status_idx'),
        ),
    ]
