# Generated by Django 5.1.3 on 2026-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('institution', 'Institution'), ('supervisor', 'Supervisor'), ('coordinator', 'Coordinator'), ('government', 'Government'), ('ngo', 'NGO'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
