# Generated by Django 5.1.3 on 2026-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_registration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('certificate', 'Certificate')], help_text='Academic level (Diploma, Degree, Masters, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address (optional)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_description',
            field=models.TextField(blank=True, help_text='Brief description of the company', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Company email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_location',
            field=models.CharField(blank=True, help_text='Company location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo (optional)', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Company contact phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, help_text='County location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume', null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_email',
            field=models.EmailField(blank=True, help_text='Institution email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Institution name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_phone',
            field=models.CharField(blank=True, help_text='Institution phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('college', 'College'), ('tvet', 'TVET'), ('institute', 'Institute')], help_text='Type of institution', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Institution logo (optional)', null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office location (optional)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Position/Title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Staff/Employee ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_institution',
            field=models.CharField(blank=True, help_text='Institution name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (optional)', null=True, upload_to='supervisor_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Company website (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Student registration/admission number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Course or program of study', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry type (Technology, Healthcare, Finance, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution/University name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills (e.g., Python, Java, Networking)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(default=1, help_text='Current year of study'),
        ),
    ]
