# Generated by Django 6.0.5 on 2026-09-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_placementprogressreport_supervisorevaluation'),
        ('students', '0004_academicqualification_referee_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='institution_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='institutions.institutionprofile'),
        ),
    ]
