# Generated by Django 6.0.5 on 2026-05-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('internship_type', models.CharField(choices=[('attachment', 'Industrial Attachment'), ('internship', 'Internship'), ('graduate_trainee', 'Graduate Trainee')], max_length=30)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('slots_available', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='employers.employerprofile')),
            ],
        ),
    ]
