# Generated by Django 6.0.5 on 2026-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_response',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted Interview'), ('declined', 'Declined Interview')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_response_note',
            field=models.TextField(blank=True),
        ),
    ]
