# Generated by Django 6.0.5 on 2026-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_applicationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmessage',
            name='deleted_for_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='deleted_for_student',
            field=models.BooleanField(default=False),
        ),
    ]
