# Generated by Django 5.1.3 on 2026-07-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('organization_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('TVET', 'TVET Institute'), ('COMPANY', 'Private Company'), ('NGO', 'Non-Governmental Organization'), ('GOVERNMENT', 'Government Agency'), ('OTHER', 'Other')], default='COMPANY', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('subscription_plan', models.CharField(default='free', max_length=50)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['organization_type'], name='organizatio_organiz_650025_idx'), models.Index(fields=['is_verified'], name='organizatio_is_veri_831d59_idx')],
            },
        ),
    ]
