# Generated by Django 6.0.5 on 2026-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('institution', 'Institution'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
