# Generated by Django 6.0.5 on 2026-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_announcement_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('student', 'Students'), ('employer', 'Employers'), ('institution', 'Institutions'), ('supervisor', 'Supervisors'), ('hod', 'Heads of Department'), ('dean', 'Deans')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('institution', 'Institution'), ('supervisor', 'Supervisor'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('admin', 'Admin')], max_length=20),
        ),
    ]
