# Generated by Django 6.0.5 on 2026-09-24 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('institutions', '0003_placementprogressreport_supervisorevaluation'),
        ('students', '0005_studentprofile_institution_profile'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, default='', max_length=100)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_assignments', to='academics.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_assignments', to='institutions.institutionprofile')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_academic_assignments', to='academics.programme')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_assignments', to='academics.schoolfaculty')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assignment', to='students.studentprofile')),
            ],
            options={
                'ordering': ['department__name', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorAcademicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_academic_assignments', to='academics.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_academic_assignments', to='institutions.institutionprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_academic_assignments', to='academics.schoolfaculty')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assignment', to='supervisors.supervisorprofile')),
            ],
            options={
                'ordering': ['department__name', 'supervisor__full_name'],
            },
        ),
    ]
