# Generated by Django 6.0.5 on 2026-09-28 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentacademicassignment_and_more'),
        ('institutions', '0003_placementprogressreport_supervisorevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('coursework_weight', models.DecimalField(decimal_places=2, default=30, help_text='Maximum CAT/coursework mark, for example 30.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('examination_weight', models.DecimalField(decimal_places=2, default=70, help_text='Maximum examination mark, for example 70.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pass_mark', models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_grade_scales_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='institutions.institutionprofile')),
            ],
            options={
                'ordering': ['institution__institution_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.CharField(blank=True, default='', max_length=80)),
                ('is_pass', models.BooleanField(default=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='academics.gradescale')),
            ],
            options={
                'ordering': ['scale', '-minimum_mark'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Dean'), ('returned', 'Returned for Correction'), ('published', 'Approved and Published')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_submissions', to='academics.studentacademicassignment')),
                ('grading_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_submissions', to='academics.gradescale')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_results_reviewed', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_submissions', to='academics.semester')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_results_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-semester__academic_year__starts_on', '-semester__number'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('examination_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_mark', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('letter_grade', models.CharField(editable=False, max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('remark', models.CharField(blank=True, default='', editable=False, max_length=80)),
                ('is_pass', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.semesterresultsubmission')),
            ],
            options={
                'ordering': ['registration__unit__code'],
            },
        ),
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Grade Created'), ('updated', 'Grade Updated'), ('submitted', 'Results Submitted'), ('returned', 'Results Returned'), ('published', 'Results Published'), ('amended', 'Published Grade Amended')], max_length=20)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_grade_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='academics.semesterresultsubmission')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='academics.studentgrade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeAmendmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_coursework_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposed_examination_mark', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Dean Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_amendments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendment_requests', to='academics.studentgrade')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentUnitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_registrations', to='academics.studentacademicassignment')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_unit_registrations_created', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_unit_registrations', to='academics.semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_registrations', to='academics.unit')),
            ],
            options={
                'ordering': ['semester__academic_year__starts_on', 'semester__number', 'unit__code'],
            },
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='academics.studentunitregistration'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_grade_scale_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scale', 'letter_grade'), name='unique_letter_grade_per_scale'),
        ),
        migrations.AddConstraint(
            model_name='semesterresultsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'semester'), name='unique_student_semester_result_submission'),
        ),
        migrations.AddConstraint(
            model_name='studentunitregistration',
            constraint=models.UniqueConstraint(fields=('assignment', 'unit', 'semester'), name='unique_student_unit_registration'),
        ),
    ]
