# Generated by Django 6.0.5 on 2026-09-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('internships', '0006_applicationmessage_deleted_for_employer_and_more'),
        ('students', '0004_academicqualification_referee_workexperience'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('institution_notes', models.TextField(blank=True)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_assignment', to='internships.application')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_assignments', to='institutions.institutionprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_assignments', to='students.studentprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_assignments', to='supervisors.supervisorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'student', 'application'), name='unique_institution_student_application_assignment')],
            },
        ),
    ]
