# Generated by Django 6.0.5 on 2026-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_placementprogressreport_supervisorevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("polytechnic", "National Polytechnic"),
                            ("tvet", "TVET Institution"),
                            ("technical_college", "Technical College"),
                            ("other", "Other"),
                        ],
                        default="college",
                        max_length=30,
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Institution directory",
                "ordering": ["name"],
            },
        ),
    ]
