# Generated by Django 6.0.5 on 2026-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(help_text='Example: yourcompany@gmail.com', max_length=254)),
                ('email_host_password', models.CharField(help_text='Use Gmail App Password, not normal Gmail password.', max_length=255)),
                ('default_from_email', models.EmailField(max_length=254)),
                ('admin_notification_email', models.EmailField(help_text='Admin email that receives new registration alerts.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
