# Generated by Django 6.0.5 on 2026-06-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Permanent Meta WhatsApp Cloud API access token.')),
                ('phone_number_id', models.CharField(help_text='Meta WhatsApp Cloud API Phone Number ID.', max_length=100)),
                ('registration_template_name', models.CharField(default='registration_otp', help_text='Approved WhatsApp template name for registration OTP messages.', max_length=100)),
                ('language_code', models.CharField(default='en_US', max_length=20)),
                ('default_country_code', models.CharField(default='254', help_text='Used when users enter local phone numbers, e.g. 254 for Kenya.', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('template_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('response_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
